name: payroll
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: any

  # Local Database
  sqflite: any
  path_provider: any
  path: any

  # Local Storage
  shared_preferences: any

  # Date & Time
  intl: any

  # UI Components
  flutter_svg: any

  # PDF Generation
  pdf: any
  printing: any

  # Security (Password Hashing)
  crypto: any

  # Form Validation
  email_validator: any
  # Firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any

flutter:
  uses-material-design: true
